name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Exclude .git using rsync
        run: apk add rsync && rsync -arv --exclude=".git" . output/
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "output/"
          destination-github-username: "hoangdung24"
          destination-repository-name: "admin-doidiem"
          user-email: conquynho.hd@gmail.com
          target-branch: dev
